"""Add order_index to Book model

Revision ID: 8b275ed54526
Revises: 69e6584e12c9
Create Date: 2024-12-01 15:59:26.722259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b275ed54526'
down_revision = '69e6584e12c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=255), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('author',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
