"""Add order_index to books

Revision ID: 941e64b8b7ad
Revises: 4e36e0b5050a
Create Date: 2024-11-29 18:08:30.440045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941e64b8b7ad'
down_revision = '4e36e0b5050a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('order_index')

    # ### end Alembic commands ###
